apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  template:
    spec:
      containers:
        - name: controller
          image: /test-case-controller:production
          imagePullPolicy: Always