apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: controller:beta
        ports:
        - containerPort: 50051
        env:
        - name: CONTROLLER_URL
          value: "50051"  
